= はじめに
[arabic]*

本書の目的は、シェルスクリプトを知ることで幸せになる人を増やすことです。 +
ここ場合のシェルスクリプトは、shだけでなくPowerShellも含めたコマンドラインシェルのスクリプトを指します。 +

私がシェルを好きになったきっかけは、Unix哲学の本「Unixという考え方」です。 +

シェルスクリプトは万能ではありません。 +
痒いところに手が届きにくいケースも少なからずあります。 +
そのようなケースでは、シェルスクリプトよりもケースに相応しい言語を採用すべきです。 +

本書ではサンプルスクリプトとしてshとPowerShellのスクリプトを記述します。筆者はmacOSでスクリプトを書いています。

繰り返しになりますが、本書の目的はシェルスクリプトを知ることで幸せになる人を増やすことです。 +
もし貴方の部下や後輩にこの本を必要としている人がいれば、本書を薦めてください。 +
願わくば、本書が人から人へと受け継がれる文化財のような存在になることを祈っています。 +

== 表記について

本書では以下の通り、明確に表記を使い分けます。

シェル:: コマンドラインシェルの中でもOSシェルと呼ばれるものを指します。具体的にはBourneShellやPowerShell
をイメージしてもらえばOKです。
シェルスクリプト:: シェルの機能を利用したバッチスクリプトを指します。
sh:: BourneShellを指します。
PowerShell:: WindowsPowerShellとPowerShell Coreを区別せずに指します。明確に区別する必要がある場合はWindowsPowerShell、PowerShell Coreとそれぞれ表記しますので注意してください。
shスクリプト:: BourneShellのシェルスクリプトを指します。
ps1スクリプト:: PowerShellのシェルスクリプトを指します。

== もくじ

. 基礎
.. シェルとは
... sh
... PowerShell
.. シェルの基本機能とスクリプトの制御構文
.. 余談：シェルスクリプトは読みづらい？
.. 余談：shとbashどちらで書くべき？

. ほんのり実践
.. shほんのり実践(ハル)
... ディレクトリに鍵生成の申請ファイルが置かれたら、解析して、鍵ファイルを生成
... コンソールアプリへの標準入力
... ディレクトリの監視
.. PowerShellほんのり実践（ナツ）
... サイトが変更されたらデータ抽出してテキストファイルに反映
... サイトの変更監視
... テキストファイルの操作
... WEBスクレイピング

. がっつり実践
.. PowerShellがっつり実践(ユキ)
... WEBスクレイピングWebDriver版
... IFTTTと連携してツイートする
... PowerShellでディープラーニング！？
... PowerShellとC#でUnix哲学志向の開発
... 余談：PowerShellと.NET

.. shがっつり実践(アキナ)
... Nim + shでお手軽開発講座
... スクリプト実行速度の計測
... 余談：シェルは万能じゃない

. アキナとユキの自作シェル
.. シェルを自作するということ
.. シェルの基本設計
... シェルのオートマトン設計
... コマンドのフォーマット設計






