= サイトの変更監視

解説者：ハル +
はじめまして、シェル研一年生のハルです。 +
この章の解説を任されたので、精一杯頑張らせていただきます。 +
ところで読者の皆さんは、サイトの更新(変更)を検知したい遠思ったことはありませんか？ +
今回はサイトの変更を検知するスクリプトの例をshとPoweShellで書いていきます。 +
なお、スクリプトの定期呼び出しには、cronやタスクスケジューラ等の外部アプリケーションを利用することにします。+

== 忙しい人のための要約
<忙しいひとのために箇条書きの要約>

== shのコード解説
以下がsh版のコードです。
[source, sh]
----
include::watch_site.sh[]
----

__N行目___の初期化処理ではスクリプトに渡された引数の初期化を行っています。 +
URL/CURRENT_FILE/LATEST_FILEの引数はデフォルト値を持っており、値が指定されなかった場合はINIT_***の値が格納されます。 +

__N行目___のsite_change_event関数は、サイトの変更を検知した際に呼び出すための関数です。 +
検知した際に実行したい処理は目的によってよく変わります。そのため、このように関数化しておくことで管理が楽になります。 +

__N行目___からメインの処理が始まります。 +

__N行目___はサイトのコンテンツをCURRENT_FILEに書き出す処理です。 +
curlはサーバとデータの送受信をするためのコマンドです。 +
curlは主にhttp/httpsの送受信で利用される印象がありますが、マニュアルページを見てみると送受信の際に使用できるプロトコルはFTP/IMAP/SMB/LDAP等、他にもあって非常に豊富です。詳細については `man curl` で確認してみてください。 +
ちなみに今回はhttpを使います。 +
curlは-sオプションを付けることで、サイレントモードと呼ばれるモードになります。
サイレントモードでは、進捗バーなどを出力しません。今回の場合はサイトのコンテンツ(厳密にはHTML)だけ欲しいため、-sオプションを付けています。
つまり `curl -s http://~省略` は{サイトのコンテンツテキスト}になります。
続く `>` はリダイレクトと呼ばれ、左の値を右に書き込む処理を表しているので、__N行目___は `{サイトのコンテンツテキスト}を$CURRENT_FILEに書き込む` 処理になります。



<ここに解説を書く>

== powershellのコード解説

以下がPowerShell版のコードです。
[source, powershell]
----
include::Watch-Site.ps1[]
----

<ここに解説を書く>

== 余談
<ここに余談を書く>

== 用語解説
<出てきた用語>:: <用語の説明をここに書く>